### ISSUE TITLE
Calling as root does not show per-user processes

### ISSUE THREAD

**Issue by slhck** [G-dH/smem#1]
Thanks for this fork!

When I do a side-by side comparison, left hand side is the user, right hand side is root:

<img width="1424" alt="image" src="https://github.com/G-dH/smem/assets/582444/b0d519ab-ca38-41b8-b39c-5f9e4f02c3ca">

I would expect that when calling as root, I get all user processes. Do you know why that is not the case?

**Comment by G-dH** [comment]
Hello! I'm not sure, I'm getting all processes when I use smem as root.

**Comment by slhck** [comment]
Yes, it's weird. This is a docker container, could that be an issue?

**Comment by G-dH** [comment]
It must be related to the permissions to the /proc content.

**Comment by slhck** [comment]
Good idea, I will check whether that's the source of the problem.

**Comment by slhck** [comment]
Must be due to Docker, it works on a regular system. Thanks for the pointer!
